\input texinfo @c -*-texinfo-*-
@c %**start of header
@include ../bookSettings.texinfo
@include copying.texinfo
@c %**end of header

@titlepage
@title The @cuis{} book
@subtitle Introduction to Programming with Smalltalk
@* @* @* @*

@alanQuoteAboutCuis
@author @writers{}

@iftex
   @page
   @vskip 0pt plus 1filll       
   @insertcopying
@end iftex
@end titlepage

@iftex
@shortcontents
@contents
@end iftex

@node Top

@alanQuoteAboutCuis

@*

Cuis is a free Smalltalk-80 environment with a specific set of goals:
being simple and powerful. It is also portable to any platform, fast
and efficient.
@*

You are reading the Cuis Book!

@top The Cuis Book

@ifnottex
  @shortcontents
  @insertcopying
  @contents
@end ifnottex

@c @menu
@c * Preface::
@c * Beginnings::
@c * The Message Way of Life::
@c * Class - Model of Communicating Entities::
@c * The Collection Way of Life::
@c * Control Flow Messaging::
@c * Visual with Morph::
@c * The Fundamentals of Morph::
@c * Events::
@c * Code Management::
@c * Debug and Exception Handling::
@c * Sharing Cuis::
@c * Documents Copyright::
@c * Summary of Syntax::
@c * The Exercises::
@c * Solutions to the Exercises::
@c * The Examples::
@c * The Figures::
@c * Spacewar! Source Code::
@c * Indexes::
@c @end menu

@tex
\global\parskip=0.5em
@end tex

@c================================================================
@c Preface
@include chapter-00/contents.texinfo
@c================================================================
@c:Part One
@c @part Part One @*The basis of @cuis{}
@c
@include chapter-01/contents.texinfo
@c
@include chapter-02/contents.texinfo
@c
@include chapter-03/contents.texinfo
@c
@include chapter-04/contents.texinfo
@c
@include chapter-05/contents.texinfo
@c
@include chapter-06/contents.texinfo
@c
@include chapter-07/contents.texinfo
@c
@include chapter-08/contents.texinfo
@c
@include chapter-09/contents.texinfo
@c
@include chapter-10/contents.texinfo
@c
@include chapter-11/contents.texinfo
@c================================================================
@c: Part Four
@c @part Part Four @*Appendices
@c Copyrighted document used in the book
@include copyrights.texinfo
@c Summary of syntax
@include syntaxSummary.texinfo
@c List of exercises
@node The Exercises
@appendix The Exercises
@listoffloats Exercise
@c Solutions of exercises
@include chapter-50/contents.texinfo
@c List of examples
@node The Examples
@appendix The Examples
@listoffloats Example
@c List of figures
@node The Figures
@appendix The Figures
@listoffloats Figure
@c The Spacewar source code
@node Spacewar! Source Code
@appendix Spacewar! Source Code
In the raw source code below, understand the ``_'' character as ``@assign{}''.
@smallformat
@verbatiminclude ../Spacewar!.pck.st
@end smallformat
@c Indexes
@node Indexes
@appendix Conceptual index
@printindex cp
@c================================================================
@c: To be filled

@c:END OF THE BOOK
@bye
