'From Cuis 5.0 [latest update: #4241] on 5 September 2020 at 12:28:07 am'!
'Description '!
!provides: 'Spacewar!!' 1 0!
SystemOrganization addCategory: #'Spacewar!!'!


!classDefinition: #CentralStar category: #'Spacewar!!'!
Object subclass: #CentralStar
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spacewar!!'!
!classDefinition: 'CentralStar class' category: #'Spacewar!!'!
CentralStar class
	instanceVariableNames: ''!

!classDefinition: #SpaceShip category: #'Spacewar!!'!
Object subclass: #SpaceShip
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spacewar!!'!
!classDefinition: 'SpaceShip class' category: #'Spacewar!!'!
SpaceShip class
	instanceVariableNames: ''!

!classDefinition: #StarField category: #'Spacewar!!'!
Object subclass: #StarField
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spacewar!!'!
!classDefinition: 'StarField class' category: #'Spacewar!!'!
StarField class
	instanceVariableNames: ''!

!classDefinition: #Torpedo category: #'Spacewar!!'!
Object subclass: #Torpedo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spacewar!!'!
!classDefinition: 'Torpedo class' category: #'Spacewar!!'!
Torpedo class
	instanceVariableNames: ''!

