@node Preface
@unnumbered Preface


What @cuis{} is: @cuis{} -- or in short Cuis -- is a portable
environment for doing, building, and sharing software.

Cuis is a journey and a process and comes with a philosophy of
reducing complexity while providing a complete, live software
development experience.

This book is an introduction and invitation to exploring Cuis.

We hope you will join us in this journey to make Cuis ever better.

@figure{Cuis,ch00-img1,12}

To make your journey with this book more enjoyable, the
@emph{Spacewar!}@footnote{@url{https://en.wikipedia.org/wiki/Spacewar!}}
project is its recurring theme. It is distilled along the book in code
examples, exercises and dedicated chapters. At the end of the book,
you will have written a replica of this historic video game.
