@node Preface
@unnumbered Preface

What @cuis{} is: Cuis is a portable environment for doing, building, and sharing software.

Cuis is a journey and a process and comes with a philosophy of reducing complexity while providing a complete, live software development experience.

This book is an introduction and invitation to exploring Cuis.

We hope you will join us in this journey to make Cuis ever better.

@figure{Cuis,A-01-img1,12}

Once unpon a time... @class{Object} gave birth to many @method{new}
children to raise a large familly of @smalltalk{allInstance size} living and vivid objects.
@smalltalkExample{
1 to: 10 by: 1 do: [:i |
   i even ifTrue: [
      i * i ] ]}

